name: Deploy
run-name: ${{ github.actor }} deploying page...
on:
    push:
        branches:
            - main
jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Main
              uses: actions/checkout@v4

            - name: Deploy to GitHub Pages
              uses: crazy-max/ghaction-github-pages@v4
              with:
                  target_branch: gh-pages
                  build_dir: ./
