name: Deploy
run-name: ${{ github.actor }} deploying page...
on:
    push:
        branches:
            - main
jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Main
              uses: actions/checkout@v4

            - name: Import GPG key
              uses: crazy-max/ghaction-import-gpg@v5
              with:
                  gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
                  passphrase: ${{ secrets.PASSPHRASE }}
                  git_user_signingkey: true
                  git_commit_gpgsign: true

            - name: Deploy to GitHub Pages
              uses: crazy-max/ghaction-github-pages@v4
              with:
                  target_branch: gh-pages
                  build_dir: ./
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
